#! /usr/bin/env bash

docker login -u="${USERNAME}" -p="${PASSWORD}" registry.cn-beijing.aliyuncs.com
for i in $(cat ./image.list); do
  o="registry.cn-beijing.aliyuncs.com/faasx/k8s/$(echo ${i} | awk -F '/' '{ print $NF }')"

  docker image pull "${i}"
  docker image tag "${i}" "${o}"
  docker image push "${o}"
done
docker logout
